<?php

namespace App\Tools\Html\Control\Select;

use App\Tools\Html\Control\BaseControl;

/**
 * Created by PhpStorm.
 * User: arts-mgcx
 * Date: 2017/2/4
 * Time: 9:40
 */
class Select extends BaseControl
{
    protected function parseEdit($tpl)
    {
        $options = [];
        foreach ($this->attribute['data'] as $key => $val) {
            $options[] = '<option value="' . $key . '" ' . ($this->default == $key ? 'selected="selected"' : '') . '>' . $val . '</option>';
        }
        $tpl = parent::parseEdit($tpl); // TODO: Change the autogenerated stub
        return str_replace([
            '__Option__',
        ], [
            implode("\r\n", $options),
        ], $tpl);
    }

    protected function checkAttribute()
    {
        parent::checkAttribute(); // TODO: Change the autogenerated stub
        if (!isset($this->attribute['data']) || !is_array($this->attribute['data'])) {
            throw new \Exception('Select attribute data is invalid');
        }
    }
}