<?php

namespace App\Tools\Html\Control\Editor;

use App\Tools\Html\Control\BaseControl;

/**
 * Created by PhpStorm.
 * User: arts-mgcx
 * Date: 2017/2/4
 * Time: 9:40
 */
class Editor extends BaseControl
{
    protected function parseEdit($tpl)
    {
        return parent::parseEdit($tpl); // TODO: Change the autogenerated stub
    }


    public function getConfigJs()
    {
        $js = "var ue = UE.getEditor('{$this->getId()}_editor');";
        $js .= "\r\n";
        $js .= "ue.addListener( 'ready', function( editor ) {";
        $js .= "\r\n";
        $js .= "UE.getEditor('{$this->getId()}_editor').setContent($('#{$this->getId()}_hidden_content').val(), false);";
        $js .= "\r\n";
        $js .= "});";
        $js .= "\r\n";//return $js;
        $js .= "ue.addListener('contentChange',function(){";
        $js .= "\r\n";
        $js .= "$('#{$this->getId()}').val(UE.getEditor('{$this->getId()}_editor').getContent());";
        $js .= "\r\n";
        $js .= "});";
        $js .= "\r\n";
        return $js;

    }
}