<?php

namespace App\Tools\Html\Control\Address;

use App\Tools\Html\Control\BaseControl;

/**
 * Created by PhpStorm.
 * User: arts-mgcx
 * Date: 2017/2/4
 * Time: 9:40
 */
class Address extends BaseControl
{
    protected function parseEdit($tpl)
    {
        return parent::parseEdit($tpl); // TODO: Change the autogenerated stub
    }

    public function getConfigJs()
    {
        return 'addressInit($(\'#' . $this->getId() . '\'),\'' . $this->default . '\');';
    }

}