<?php

namespace App\Tools\Html\Control\DateLong;
use App\Tools\Html\Control\BaseControl;
/**
 * Created by PhpStorm.
 * User: arts-mgcx
 * Date: 2017/2/4
 * Time: 9:40
 */
class DateLong extends BaseControl
{
    protected function parseEdit($tpl)
    {
        return parent::parseEdit($tpl); // TODO: Change the autogenerated stub
    }
}